-- The salon identity, barber, and service remain fixed in application code for
-- this single-business POC. Add local-only customer and appointment fixtures
-- here when the booking flow needs them.
